In [8]:
import numpy as np

#行列定義
A  = np.array([[0,1],[2,3],[4,5]])
B  = np.array([[0,1,2,3],[4,5,6,7]])

#積の計算
C = np.dot(A,B)

#積の計算の表示
print(C)

#最大値
max = C.max()

#表示
print(max)



[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
